name: Comprehensive Test
on:
  workflow_dispatch:
    inputs: 
      gitee_owner:
        description: 'Gitee 用户名, 项目URL中可获取'
        required: true
        default: NiceLeee
      gitee_repo:
        description: 'Gitee 项目名, 项目URL中可获取'
        required: true
        default: NiceLeee
      gitee_token:
        description: 'Gitee api token'
        required: true
jobs:
  # Job 1: 测试单文件创建release和相关操作
  test-single-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.ref }}
        
    - name: Test create release with single file
      id: create_release_single
      uses: ./
      with:
        gitee_action: create_release
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-single-${{ github.run_number }}
        gitee_release_name: Single File Test v1.0-${{ github.run_number }}
        gitee_release_body: 'Gitee single file release test'
        gitee_target_commitish: master
        gitee_file_name: 'single-test.txt'
        gitee_file_path: 'LICENSE'
          
    - name: Test upload additional single file to existing release
      uses: ./
      with:
        gitee_action: upload_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_release_id: ${{ steps.create_release_single.outputs.release-id }}
        gitee_file_name: 'additional-single.txt'
        gitee_file_path: 'README.md'

    - name: Test upload using tag_name (single)
      uses: ./
      with:
        gitee_action: upload_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-single-${{ github.run_number }}
        gitee_file_name: 'tag-upload-single.txt'
        gitee_file_path: 'action.yml'
        
    - name: Test update asset
      uses: ./
      with:
        gitee_action: update_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-single-${{ github.run_number }}
        gitee_old_asset_name: 'single-test.txt'
        gitee_new_file_path: 'requirements.txt'
        
    - name: Test delete specific asset
      uses: ./
      with:
        gitee_action: delete_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-single-${{ github.run_number }}
        gitee_delete_assets: 'tag-upload-single.txt'
        
    - name: Test delete release
      uses: ./
      with:
        gitee_action: delete_release
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-single-${{ github.run_number }}

  # Job 2: 测试多文件创建release和相关操作
  test-multi-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.ref }}
        
    - name: Test create release with multiple files
      id: create_release_multi
      uses: ./
      with:
        gitee_action: create_release
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-multi-${{ github.run_number }}
        gitee_release_name: Multi File Test v1.0-${{ github.run_number }}
        gitee_release_body: 'Gitee multi file release test'
        gitee_target_commitish: master
        gitee_files: |
          LICENSE
          README.md
          action.yml
          
    - name: Test upload additional multiple files to existing release
      uses: ./
      with:
        gitee_action: upload_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_release_id: ${{ steps.create_release_multi.outputs.release-id }}
        gitee_files: |
          requirements.txt
          gitee_release.py

    - name: Test upload using tag_name (multi)
      uses: ./
      with:
        gitee_action: upload_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-multi-${{ github.run_number }}
        gitee_file_name: 'tag-upload-multi.txt'
        gitee_file_path: 'LICENSE'
        
    - name: Test delete multiple assets
      uses: ./
      with:
        gitee_action: delete_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-multi-${{ github.run_number }}
        gitee_delete_assets: |
          tag-upload-multi.txt
          LICENSE
        
    - name: Test delete release
      uses: ./
      with:
        gitee_action: delete_release
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-multi-${{ github.run_number }}

  # Job 3: 测试使用已存在release ID的场景
  test-existing-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.ref }}
        
    - name: Create base release for testing
      id: create_base_release
      uses: ./
      with:
        gitee_action: create_release
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-existing-${{ github.run_number }}
        gitee_release_name: Existing Release Test v1.0-${{ github.run_number }}
        gitee_release_body: 'Test using existing release ID'
        gitee_target_commitish: master
        
    - name: Test upload single file to existing release by ID
      uses: ./
      with:
        gitee_action: upload_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_release_id: ${{ steps.create_base_release.outputs.release-id }}
        gitee_file_name: 'existing-single.txt'
        gitee_file_path: 'LICENSE'
        
    - name: Test upload multiple files to existing release by ID
      uses: ./
      with:
        gitee_action: upload_asset
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_release_id: ${{ steps.create_base_release.outputs.release-id }}
        gitee_files: |
          README.md
          action.yml
          requirements.txt
        
    - name: Test delete release
      uses: ./
      with:
        gitee_action: delete_release
        gitee_owner: ${{ inputs.gitee_owner }}
        gitee_repo: ${{ inputs.gitee_repo }}
        gitee_token: ${{ inputs.gitee_token }}
        gitee_tag_name: v1.0-existing-${{ github.run_number }}
